---
# ------------------------------- #
#   Classic Theme Configuration   #
# ------------------------------- #

theme:
  name: classic
  # path to theme stylesheets directory
  stylesheets_dir: stylesheets
  # path to theme javascripts directory
  javascripts_dir: javascripts

js_lib: ['lib/jquery-1.9.1.js', 'lib/jquery.cookie.js', 'lib/**/*']


simple_search: http://google.com/search
favicon: /octopress-favicon.png

# To change the layout's default sidebar Add a new sidebar source/_includes/sidebars/your_sidebar.html
# then make changes below, eg. post_sidebar: your_sidebar.html

sidebar:
  recent_posts: 5             # Posts in the sidebar Recent Posts section

excerpt:
  link: "Continue reading →"  # "Continue reading" link text at the bottom of excerpted articles
  feed: false                 # Excerpt articles in the feed

permalink_label:
  post: "Permalink"
  feed: "★ Permalink"


# Choose how you want to indicate posts, linkposts and permalinks 
#
title_marker:
  # Default: normal post titles aren't marked
  post: 
    marker:         false
    position:       before
    feed_position:  before

  # Default: link posts titles are followed with an arrow
  linkpost:
    marker:         "→"
    position:       after
    feed_position:  after

